version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: seejang-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seejang
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - seejang-network

  app:
    build: .
    container_name: seejang
    restart: always
    depends_on:
      - mysql
      - elasticsearch
    ports:
      - "8080:8080"
    networks:
      - seejang-network

  elasticsearch:
    image: elasticsearch:8.15.5
    container_name: seejang-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - node.name=seejang-elasticsearch
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=passwd
      - xpack.security.transport.ssl.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - seejang-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: kibana:8.6.0
    container_name: seejang-kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://seejang-elasticsearch:9200
    networks:
      - seejang-network
    depends_on:
      - elasticsearch

volumes:
  mysql_data:
  es_data:

networks:
  seejang-network:
    driver: bridge
